"""add indexes on reporter_id and audit user_id

Revision ID: 700352af4b69
Revises: 46f01eee29a3
Create Date: 2026-06-28 22:19:25.847854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700352af4b69'
down_revision: Union[str, Sequence[str], None] = '46f01eee29a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_issues_reporter_id'), 'issues', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_reporter_id'), table_name='issues')
    # ### end Alembic commands ###
